.\" Manpage for copyso.
.\" Contact oks-mgn@mail.ru to correct errors or typos.
.TH COPYSO 1 "15 Июня 2019" "0.1" "copyso man page"
.SH ИМЯ
copyso \- копирует бинарные исполняемые файлы и их зависимости
.SH ИСПОЛЬЗОВАНИЕ
.B copyso
[\fIОПЦИИ\fR] \fIфайл\fR ... \fIцелевой_каталог\fR
.SH ОПИСАНИЕ
.B copyso
копирует бинарные исполняемые файлы (elf и so) в целевой каталог.
Программа полезна при создании собственных загрузочных дисков.
Символьные ссылки копируются как ссылки, их цель (на что они ссылаются) так же обрабатывается.
Другие исполняемые файлы (скрипты bash, perl, python ...) и прочие файлы просто копируются.
При копировании сохраняется структура каталогов, файлы помещаются в те же подкаталоги.
Программа не перезаписывает существующие файлы.
\fBcopyso\fR использует \fBobjdump \-p\fR чтобы прочитать зависимости.
.TP
\fIфайл\fR
может быть простым файлом, символьной ссылкой или каталогом.
.TP
\fIцелевой_каталог\fR
куда копировать.
.SH ОПЦИИ
Обязательные аргументы для длинных опций обязательны и для коротких.
.TP
\fB\-r\fR, \fB--root\fR=\fIОТКУДА\fR
каталог, в котором искать файлы для копирования, например alt_arch/x86.
По умолчанию используется корневой каталог.
.TP
   \fB--srclib\fR=\fIОТКУДА\fR
каталог, в котором искать so-файлы для копирования и файл ld.so.conf.
По умолчанию равен \fB--root\fR.
.TP
   \fB--dstlib\fR=\fIКУДА\fR
подкаталог относительно целевого каталога, в который записывать so-файлы.
По умолчанию записывает, сохраняя их относительное положениее.
.TP
\fB\-l\fR, \fB--link\fR
пытаться делать жесткие ссылки на файлы, а не копировать их.
Это ускорит работу с сэкономит место на диске.
При ошибках отображается только первая, чтобы не замусоривать экран.
.TP
\fB\-p\fR, \fB--path\fR
использовать переменную окружения PATH для поиска копируемых файлов.
Например, если PATH=/bin:/sbin и --root=/x86-64, то файлы будут искаться в /x86-64/bin и /x86-64/sbin.
.TP
\fB\-v\fR, \fB--verbose\fR
показывать выполняемые действия и дополнительную информацию.
.TP
\fB--help\fR
отобразить краткую справку.
.TP
\fB--version\fR
показать версию программы.
.SH ПРИМЕРЫ
.TP
copyso /bin/sh my_livecd
копирует /bin/sh в ./my_livecd/bin/sh.
Если /bin/sh, например, является символьной ссылкой на /bin/bash, /bin/bash будет так же скопирован.
Эта команда так же скопирует требуемые so-файлы: /lib64/libc.so.6 в ./my_livecd/lib64/libc.so.6 и так далее.
.TP
copyso -l /bin/sh my_livecd
вместо копирования будут сделаны жёсткие ссылки.
.TP
copyso -p sh bc my_livecd
будет прочитана переменная окружения PATH.
Поскольку "sh" расположена в /bin/sh, будет скопирована /bin/sh в ./my_livecd/bin/sh.
Если "bc" расположена в /usr/bin/bc, скопирует её в ./my_livecd/usr/bin/bc.
Далее смотри первый пример.
.TP
copyso /bin my_livecd
скопирует каждый файл из "bin" (только из этого каталога, не подкаталогов) в ./my_livecd/bin/.
Далее, например, если /bin/awk является символьной ссылкой на /usr/bin/gawk, то /usr/bin/gawk будет так же скопирован.
Требуемые so-файлы так же будут скопированы.
.TP
copyso --dstlib=lib /bin my_livecd
как и предыдущий пример, но каждый so-файл будет скопирован именно в ./my_livecd/lib, а не во всякие lib/x86_64-linux-gnu-....
.TP
copyso --root=/my_src bin sbin my_livecd
скопирует файлы из /my_src/bin в ./my_livecd/bin, а из /my_src/sbin в ./my_livecd/sbin.
.TP
copyso --root=/my_src --srclib=/ bin my_livecd
скопирует файлы из /my_src/bin в ./my_livecd/bin, но требуемые so-файлы будут скопированы из /lib, /usr/lib, ... в ./my_livecd/lib, ./my_livecd/usr/lib, ...
Список каталогов с so-файлами будет считываться из /etc/ld.so.conf.
.TP
copyso --root=/my_src --srclib=/1 bin my_livecd
скопирует файлы из /my_src/bin в ./my_livecd/bin, но требуемые so-файлы будут скопированы из /1/lib, /1/usr/lib, ... в ./my_livecd/lib, ./my_livecd/usr/lib, ...
Список каталогов с so-файлами будет считываться из /1/etc/ld.so.conf.
.SH СМОТРИ ТАКЖЕ
objdump(1)
.SH BUGS
Нет известных.
.SH AUTHOR
Oshepkov Konstantin (oks-mgn@mail.ru)
