.\" Manpage for copyso.
.\" Contact oks-mgn@mail.ru to correct errors or typos.
.TH COPYSO 1 "04 Мая 2019" "0.1" "copyso man page"
.SH ИМЯ
copyso \- копирует бинарные исполняемые файлы и их зависимости
.SH ИСПОЛЬЗОВАНИЕ
.B copyso
[\fIОПЦИИ\fR] \fIчто\fR ... \fIцелевой_каталог\fR
.SH ОПИСАНИЕ
.B copyso
копирует бинарные исполняемые файлы (elf и so) в целевой каталог.
Программа полезна при создании собственных загрузочных дисков.
Символьные ссылки копируются как ссылки, их цель (на что они ссылаются) так же обрабатывается.
Другие исполняемые файлы (скрипты bash, perl, python ...) и прочие файлы просто копируются.
При копировании сохраняется структура каталогов, файлы помещаются в те же подкаталоги.
Программа не перезаписывает существующие файлы.
\fBcopyso\fR использует \fBobjdump \-p\fR чтобы прочитать зависимости.
.TP
\fIчто\fR
может быть файлом, символьной ссылкой или каталогом.
.TP
\fIцелевой_каталог\fR
куда копировать.
.SH ОПЦИИ
Обязательные аргументы для длинных опций обязательны и для коротких.
.TP
\fB\-r\fR, \fB--root\fR=\fIFROM\fR
каталог, в котором искать файлы для копирования, например alt_arch/x86.
По умолчанию используется корневой каталог.
.TP
\fB\-l\fR, \fB--link\fR
пытаться делать жесткие ссылки на файлы, а не копировать их.
Это ускорит работу с сэкономит место на диске.
При ошибках отображается только первая, чтобы не замусоривать экран.
.TP
\fB\-v\fR, \fB--verbose\fR
показывать выполняемые действия и дополнительную информацию.
.TP
\fB--help\fR
отобразить краткую справку.
.TP
\fB--version\fR
показать версию программы.
.SH ПРИМЕР
copyso --root=/bin sh mkdir mount cat cut my_livecd/bin
.SH СМОТРИ ТАКЖЕ
objdump(1)
.SH BUGS
Нет известных.
.SH AUTHOR
Oshepkov Konstantin (oks-mgn@mail.ru)
